Practice with Classes-2(Создание методов классов)
eugene-okulik/Kirill_Dechko pull request #13
Opened 2024-03-09 08:42 UTC by kirilldechko

2024-03-09 19:30 UTC, eugene-okulik requested changes
А чо это? Это ж то же, что я на занятии показывал.

2024-03-09 19:32 UTC, kirilldechko commented
Это я себе для конспектирования скопировал…

Best Regards,

*Kiryl DZECHKA*



*+375 44 579 76 78*   *Email: ***@***.***
***@***.***>*

*Grodno,* *Belarus *(GMT+3)


Сб, 9 марта 2024 г. в 22:30, Eugeny Okulik ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> А чо это? Это ж то же, что я на занятии показывал.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/eugene-okulik/Kirill_Dechko/pull/13#pullrequestreview-1926294640>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AX5J5R6DULO3EQGMA2TCQJDYXNPOJAVCNFSM6AAAAABEN6F2JSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSMRWGI4TINRUGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-03-09 19:33 UTC, kirilldechko commented
А домашка в task1

2024-03-09 19:35 UTC, eugene-okulik commented
> А домашка в task1

А в task1 пусто

2024-03-09 19:36 UTC, kirilldechko commented
Ща повторю…

Best Regards,

*Kiryl DZECHKA*



*+375 44 579 76 78*   *Email: ***@***.***
***@***.***>*

*Grodno,* *Belarus *(GMT+3)


Сб, 9 марта 2024 г. в 22:35, Eugeny Okulik ***@***.***>:

> А домашка в task1
>
> А в task1 пусто
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/eugene-okulik/Kirill_Dechko/pull/13#issuecomment-1986957741>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AX5J5R2GBKQJ5BKWGDLRQSDYXNQBJAVCNFSM6AAAAABEN6F2JSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSOBWHE2TONZUGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-03-10 07:58 UTC, eugene-okulik requested changes

2024-03-10 07:58 UTC, eugene-okulik commented on homework/kirill_dechko/lesson_12/new_task_1.py
> +        self.val_fl = val_fl
Привеольно, что ты сделал какие-то методы, которые сами вычисляют свойства цветов. Ещё круче было бы сделать, чтобы эти свойства при создании сразу и высчитывались. Для этого нужно вызвать все эти методы внутри `__init__`:
```python
def __init__(self, days_in_shop: int, height: int, long_live: int, color: str, price: int, name: str, val_fl: int):
    self.freshness = days_in_shop
    self.height = height
    self.long_live = long_live
    self.color = color
    self.price = price
    self.name = name
    self.val_fl = val_fl
    self.freshness_level()
    self.height_category()
    self.longevity()
    self.color_uniqueness()
```

2024-03-10 07:58 UTC, eugene-okulik commented on homework/kirill_dechko/lesson_12/new_task_1.py
> +        return unic_val
Методы сортировки у тебя сортируют сам параметр и возвращают отсортированный список этого параметра. Т.е. здесь возвращается список свжестей. А должен возвращаться список объектов цветов. Если в исначальном списке у тебя было например так: роза со свежестью 5, тюльпан со свежестью 2 и лилия со свежестью 1, то результатом этого метода должно стать: лилия со свежестью 1, тюльпан со свежестью 2, роза со свежестью 5, а не как сейчас 1, 2, 5  
Типа если тебе нужно расположить на столе карандаши в порядке возрастания их длины, результат же будет не сантиметры длин карандашей, а правильно расположенные карандаши.

2024-03-11 07:25 UTC, eugene-okulik requested changes
В переменной  self.flowers у тебя хранятся цветы в неотсортированном виде. Тебе нужно сделать так, чтобы твои методы или переделывали сортировку внутри этой переменной или возвращали этот список, который хранится в  self.flowers, в отсортированном виде.

2024-03-11 07:25 UTC, eugene-okulik commented on homework/kirill_dechko/lesson_12/new_task_1.py
> +        return unic_val
Этот метод всё еще возвращает цвета, а не цветы

2024-03-11 07:25 UTC, eugene-okulik commented on homework/kirill_dechko/lesson_12/new_task_1.py
> +        return names
Этот метода возвращает названия, а не цветы

2024-03-11 07:25 UTC, eugene-okulik commented on homework/kirill_dechko/lesson_12/new_task_1.py
> +        return names
И эти методы возвращают названия, а не цветы.

2024-03-11 20:41 UTC, eugene-okulik approved these changes

2024-03-11 20:41 UTC, eugene-okulik commented on homework/kirill_dechko/lesson_12/new_task_1.py
> +        return sorted_price
Круто. Ты справился. Можно было сделать всё одним универсальным методом
```python
 def sort_bucket(self, key):
    sorted_flowers = sorted(self.flowers, key=lambda flower: getattr(flower, key))
    return sorted_flowers
```

2024-03-11 20:41 UTC, eugene-okulik commented on homework/kirill_dechko/lesson_12/new_task_1.py
> +# print(f"Сортировка по параметру цена - {sort_bucket}")"""
Не оставляй закомменченный код в готовой работе.

2024-03-11 20:41 UTC, eugene-okulik commented on homework/kirill_dechko/lesson_12/new_task_1.py
> +        return list(set(matching_flowers))
Эта штука тоже возвращает не найденные цветы, а только имена найденных цветов.  
Прикинь, тебе говорят "принеси мне розу", а ты вместо цветка приносишь слово "Роза"  
Но всё, отстаю от тебя, а то пошлёшь еще )))

2024-03-11 20:41 UTC, merged