Python_control_point
eugene-okulik/Kirill_Dechko pull request #19
Opened 2024-03-30 08:40 UTC by kirilldechko

2024-03-31 10:23 UTC, eugene-okulik requested changes
Вот так работает
```
python search_logs.py --path_to_file ../../eugene_okulik/data/logs/ --search_param WARN --start_date "2022-02-03 09:07:32.360" --operator ">"
```
А вот так не работает
```
python search_logs.py --path_to_file ../../eugene_okulik/data/logs/ --search_param WARN
```
Получается, поискать можно только указав дату. Просто найти в логах нужный текст не получится.
Когда справляешься со всем и запускаешь, работает хорошо . Но как-то слишком много ограничений. Все параметры, которые являются обязательными, можно указать как позиционные (в видео к заданию я показывал как это делать). Например, обязательным должен быть путь к файлу или папке, так как без логов запуск этой штуки не имеет смысла. Ну и плюч то, что в комментах писал.

2024-03-31 10:23 UTC, eugene-okulik commented on homework/kirill_dechko/lesson_17_python_control_point/search_logs.py
> +if args.nsp and args.nsp != 'nsp':
У этого аргумента значение можно вводить только == nsp?

2024-03-31 10:23 UTC, eugene-okulik commented on homework/kirill_dechko/lesson_17_python_control_point/search_logs.py
> +elif args.full_log and args.full_log != 'fl':
Судя по всему, этим аргументом ты хочешь воспользоваться как просто вкл/выкл - для этого есть True/False. И в агрументах это настраивается так
```python
full_log = parser.add_argument("-FL", "--full_log", action="store_true", help="To show full logs")
```
В итоге будет: если этот флаг указали, то его значение - True, если не указали - значение False

2024-03-31 10:23 UTC, eugene-okulik commented on homework/kirill_dechko/lesson_17_python_control_point/search_logs.py
> +        if args.search_param and args.nsp:  # если search_param и nsp в запросе и nsp корректен
Похоже, что ты сделал так, что когда юзер будет искать слово, то ему нужно указать: искать места где этого слова нет (тогда nsp нужно указать со значением 'nsp'?), а если нужно искать места, где это слово есть, то он не указывается этот nsp.  
Но задумка в другом: пользователь говорит, что он ищет всё, где есть слово "WARN" и видит, что нашлось 50 результатов, тогда он ищет всё , где есть слово "WARN", но нет слова "answer" - и видит там что-то около 3-х результатов.

2024-03-31 10:30 UTC, kirilldechko commented
Все твои догадки подтверждаю)… исправлю

Best Regards,

*Kiryl DZECHKA*



*+375 44 579 76 78*   *Email: ***@***.***
***@***.***>*

*Grodno,* *Belarus *(GMT+3)


Вс, 31 марта 2024 г. в 13:24, Eugeny Okulik ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Вот так работает
>
> python search_logs.py --path_to_file ../../eugene_okulik/data/logs/ --search_param WARN --start_date "2022-02-03 09:07:32.360" --operator ">"
>
> А вот так не работает
>
> python search_logs.py --path_to_file ../../eugene_okulik/data/logs/ --search_param WARN
>
> Получается, поискать можно только указав дату. Просто найти в логах нужный
> текст не получится.
> Когда справляешься со всем и запускаешь, работает хорошо . Но как-то
> слишком много ограничений. Все параметры, которые являются обязательными,
> можно указать как позиционные (в видео к заданию я показывал как это
> делать). Например, обязательным должен быть путь к файлу или папке, так как
> без логов запуск этой штуки не имеет смысла. Ну и плюч то, что в комментах
> писал.
> ------------------------------
>
> In homework/kirill_dechko/lesson_17_python_control_point/search_logs.py
> <https://github.com/eugene-okulik/Kirill_Dechko/pull/19#discussion_r1545572557>
> :
>
> > +# Аргументы которые принимает программа, их описание: краткое имя, полное имя, тип данных.
> +start_date = parser.add_argument("-S", "--start_date", type=str,
> +                                 help="Start date for the search (format: yyyy-mm-dd hh:mm:ss.SSS)")
> +end_date = parser.add_argument("-E", "--end_date", type=str,
> +                               help="End date for the search (format: yyyy-mm-dd hh:mm:ss.SSS)")
> +operator = parser.add_argument("-O", "--operator", type=str,
> +                               help="Comparison operator: '<', '>', '=', '><'")
> +path_to_file = parser.add_argument("-P", "--path_to_file", type=str,
> +                                   help="Path to a file or directory containing the file")
> +search_param = parser.add_argument("-SP", "--search_param", type=str, help="Any words to find rows")
> +nsp = parser.add_argument("-NSP", "--nsp", type=str, help="No search params (nsp)")
> +full_log = parser.add_argument("-FL", "--full_log", type=str, help="To show full logs")
> +args = parser.parse_args()
> +
> +# Проверка корректности параметров nsp и full_log введенных пользователем в консоли
> +if args.nsp and args.nsp != 'nsp':
>
> У этого аргумента значение можно вводить только == nsp?
> ------------------------------
>
> In homework/kirill_dechko/lesson_17_python_control_point/search_logs.py
> <https://github.com/eugene-okulik/Kirill_Dechko/pull/19#discussion_r1545573506>
> :
>
> > +                                 help="Start date for the search (format: yyyy-mm-dd hh:mm:ss.SSS)")
> +end_date = parser.add_argument("-E", "--end_date", type=str,
> +                               help="End date for the search (format: yyyy-mm-dd hh:mm:ss.SSS)")
> +operator = parser.add_argument("-O", "--operator", type=str,
> +                               help="Comparison operator: '<', '>', '=', '><'")
> +path_to_file = parser.add_argument("-P", "--path_to_file", type=str,
> +                                   help="Path to a file or directory containing the file")
> +search_param = parser.add_argument("-SP", "--search_param", type=str, help="Any words to find rows")
> +nsp = parser.add_argument("-NSP", "--nsp", type=str, help="No search params (nsp)")
> +full_log = parser.add_argument("-FL", "--full_log", type=str, help="To show full logs")
> +args = parser.parse_args()
> +
> +# Проверка корректности параметров nsp и full_log введенных пользователем в консоли
> +if args.nsp and args.nsp != 'nsp':
> +    print(Fore.LIGHTRED_EX + f"Incorrect value for nsp, must be 'nsp', not {args.nsp}" + Style.RESET_ALL)
> +elif args.full_log and args.full_log != 'fl':
>
> Судя по всему, этим аргументом ты хочешь воспользоваться как просто
> вкл/выкл - для этого есть True/False. И в агрументах это настраивается так
>
> full_log = parser.add_argument("-FL", "--full_log", action="store_true", help="To show full logs")
>
> В итоге будет: если этот флаг указали, то его значение - True, если не
> указали - значение False
> ------------------------------
>
> In homework/kirill_dechko/lesson_17_python_control_point/search_logs.py
> <https://github.com/eugene-okulik/Kirill_Dechko/pull/19#discussion_r1545574719>
> :
>
> > +                        yield line
> +        except FileNotFoundError:
> +            print(Fore.LIGHTRED_EX + "ERROR! No such file or directory" + Style.RESET_ALL)
> +
> +    # Поиск слова и вывод 150 символов до и после слова
> +    def display_context_around_word(text, word, context_length=151):
> +        index = text.find(word)  # определение индекса указанного слова
> +        start_index = max(0, index - context_length)  # вычисляет начальный индекс слова
> +        end_index = min(len(text), index + len(word) + context_length)  # вычисляет конечный индекс слова
> +        context = text[start_index:end_index]  # помещаем в переменную 150 символов до -слово- и 150 символов после
> +        return context
> +
> +    find_rows_param = []  # список для заполнения данными удовлетворяющими поиску
> +
> +    def is_search_params():  # Поиск строк по параметрам указанным пользователем (nsp, full_log, search_param)
> +        if args.search_param and args.nsp:  # если search_param и nsp в запросе и nsp корректен
>
> Похоже, что ты сделал так, что когда юзер будет искать слово, то ему нужно
> указать: искать места где этого слова нет (тогда nsp нужно указать со
> значением 'nsp'?), а если нужно искать места, где это слово есть, то он не
> указывается этот nsp.
> Но задумка в другом: пользователь говорит, что он ищет всё, где есть слово
> "WARN" и видит, что нашлось 50 результатов, тогда он ищет всё , где есть
> слово "WARN", но нет слова "answer" - и видит там что-то около 3-х
> результатов.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/eugene-okulik/Kirill_Dechko/pull/19#pullrequestreview-1970132568>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AX5J5R5WWR2R2VHJCHVGSPTY27P5JAVCNFSM6AAAAABFPMK7H2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNZQGEZTENJWHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-04-02 07:55 UTC, eugene-okulik approved these changes
Клёво работает. Еще бы то слово, которое искали, подсвечивалось каки-нибудь цветом, ваще красота бы была ))

2024-04-02 07:55 UTC, merged