lesson_4 practice with data types
eugene-okulik/Kirill_Dechko pull request #3
Opened 2024-02-19 16:29 UTC by kirilldechko

2024-02-20 07:45 UTC, eugene-okulik requested changes

2024-02-20 07:45 UTC, eugene-okulik commented on homework/kirill_dechko/lesson_4/task_1.py
> +#  print(my_dict['tuple'][-1])
А чего закомментировал эту строку?

2024-02-20 07:45 UTC, eugene-okulik commented on homework/kirill_dechko/lesson_4/task_1.py
> +my_dict['dict']['i am a tuple'] = '2805'
В задании было

> добавьте элемент с ключом ('i am a tuple',) и любым значением

А ты выполнил так, как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

Название ключа подсказывает чем должен быть этот ключ.

2024-02-20 08:51 UTC, eugene-okulik requested changes

2024-02-20 08:51 UTC, eugene-okulik commented on homework/kirill_dechko/lesson_4/task_1.py
> +my_dict['dict']['i am a tuple'] = (2, 8, 0, 5)
Ты изменил значение, а нужно было ключ. Но мыслишь в правильном направлении

2024-02-20 08:51 UTC, kirilldechko commented on homework/kirill_dechko/lesson_4/task_1.py
> +my_dict['dict']['i am a tuple'] = (2, 8, 0, 5)
)))

2024-02-21 09:07 UTC, eugene-okulik approved these changes

2024-02-21 09:07 UTC, merged